### ISSUE TITLE
Pasting response as indicated but questions are not loading.

### ISSUE THREAD

**Issue by ghost** [jackdh/better-jon-bonso-exam-host#2]
## Description

Pasting response as indicated but questions are not loading

## Steps to reproduce

FIRST LINE:
[{"_class":"assessment","id":14126156,"assessment_type":"multiple-choice","prompt":{"explanation":"<p>Scaling based on a schedule allows you to scale your 

LAST LINE:
to protect the data of your clients.  Which of the following is the most suitable solution to mitigate these kinds of attacks?","related_lectures":[]}

**Comment by jackdh** [comment]
Looks like that last line is missing the closing square bracket `]`

If that doesn't work please send me the questions in a secret https://gist.github.com to https://www.reddit.com/user/jackdh

**Comment by ghost** [comment]
That worked. Thank you very much.
